name: shell commands
on: "push"

jobs:
  run-shell-command:
    runs-on: Ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo string
        run: echo "Hello"
      - name: multiline script
        run: |
          node -v
          pwd

run-windows-commands:
  runs-on: windows Ubuntu-latest
  steps:
    - name : Directory
      run: Get-Location
    - name: Directory using bash
      run: pwd
      shell: bash