name: Terraform

on: [push]
 
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      runs-on:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Terraform  
        uses: Hashicorp/setup-terraform@v3
        with:
          terraform version: 1.1.9

      - name: init
        run: terraform init

      - name: format
        run : terraform fmt - check

      - name: validate
        run: terraform validate
        


        

    

